### ISSUE TITLE
Max images

### ISSUE THREAD

**Issue by 215MMS** [215MMS/FallsWCC#147]
In 'testing mode' (when music plays) the app isn't recognising the 'max images' command. Now getting multiple images when the max images is still set to 3. (jcb)

**Comment by philiprbrenan** [comment]
Thank you for reporting this - I am looking into it!

**Comment by philiprbrenan** [comment]
Thank you for reporting this - I am looking into it!

**Comment by philiprbrenan** [comment]
I have improved the code and tested it on coreliu.org - please let me know if a newly installed version of this app continues to exhibit these problems?
